apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: retail-app
  labels:
    app: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: public.ecr.aws/aws-containers/retail-store-sample-app-checkout:0.6.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: CARTS_ENDPOINT
          value: "http://carts.retail-app.svc.cluster.local"
        - name: ORDERS_ENDPOINT
          value: "http://orders.retail-app.svc.cluster.local"
        resources:
          limits:
            memory: 512Mi
            cpu: "500m"
          requests:
            memory: 256Mi
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: retail-app
  labels:
    app: checkout
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: checkout