apiVersion: v1
kind: Namespace
metadata:
  name: retail-app
  labels:
    name: retail-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    # This acts as the link matching this Kubernetes account directly to our custom IAM role
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxxx:role/project-bedrock-alb-controller-role
    # NOTE: When you return and initialize the active cluster, we will replace the 'xxxxxxxxxxxx' 
    # placeholder string with your real active AWS account ID instantly via a simple terminal command!